import type { DraftElementKind, MepElementKind, ParametricFamilyMetadata } from "../types";

export type FamilyCategory = "wall" | "slab" | "roof" | "column" | "door" | "window" | "mep-equipment" | "mep-fixture";
export type FamilyParameterType = "length" | "number" | "text";
export interface FamilyParameter { key: string; label: string; type: FamilyParameterType; defaultValue: number | string; unit?: string; }
export interface FamilyDefinition { id: string; category: FamilyCategory; name: string; description: string; types: string[]; typeParameters: FamilyParameter[]; instanceParameters: FamilyParameter[]; host: "none" | "level" | "wall" | "ceiling" | "floor"; metadata: Record<string, string>; }
const p = (key: string, label: string, type: FamilyParameterType, defaultValue: number | string, unit?: string): FamilyParameter => ({ key, label, type, defaultValue, unit });
const dims = (w: number, d: number, h: number): FamilyParameter[] => [p("width", "Width", "length", w, "m"), p("depth", "Depth", "length", d, "m"), p("height", "Height", "length", h, "m")];

export const FAMILY_LIBRARY: FamilyDefinition[] = [
  { id: "wall-basic", category: "wall", name: "Basic Wall", description: "Layered architectural wall placeholder.", types: ["Exterior", "Interior", "Curtain"], typeParameters: [p("thickness", "Thickness", "length", 0.2, "m"), p("fireRating", "Fire rating", "text", "Unrated")], instanceParameters: [p("topOffset", "Top offset", "length", 0, "m")], host: "level", metadata: { discipline: "Architecture", sourcePattern: "Revit/Archicad/Vectorworks" } },
  { id: "slab-basic", category: "slab", name: "Basic Slab", description: "Structural or finish floor slab.", types: ["Structural", "Finish", "Roof deck"], typeParameters: [p("thickness", "Thickness", "length", 0.2, "m"), p("material", "Material", "text", "Concrete")], instanceParameters: [p("slope", "Slope", "number", 0, "%")], host: "level", metadata: { discipline: "Architecture/Structure" } },
  { id: "roof-basic", category: "roof", name: "Basic Roof", description: "Parametric roof plane placeholder.", types: ["Flat", "Gable", "Hip"], typeParameters: [p("thickness", "Thickness", "length", 0.25, "m"), p("slope", "Slope", "number", 2, "%")], instanceParameters: [p("overhang", "Overhang", "length", 0.3, "m")], host: "level", metadata: { discipline: "Architecture" } },
  { id: "column-basic", category: "column", name: "Structural Column", description: "Vertical structural member.", types: ["Concrete", "Steel", "Timber"], typeParameters: dims(0.4, 0.4, 3), instanceParameters: [p("baseOffset", "Base offset", "length", 0, "m")], host: "level", metadata: { discipline: "Structure" } },
  { id: "door-single", category: "door", name: "Single Door", description: "Hosted door opening and leaf.", types: ["Single flush", "Single glazed", "Fire rated"], typeParameters: [p("width", "Width", "length", 0.9, "m"), p("height", "Height", "length", 2.1, "m")], instanceParameters: [p("sill", "Sill", "length", 0, "m"), p("handing", "Handing", "text", "Left")], host: "wall", metadata: { discipline: "Architecture" } },
  { id: "window-basic", category: "window", name: "Basic Window", description: "Hosted window opening and frame.", types: ["Fixed", "Casement", "Curtain wall"], typeParameters: [p("width", "Width", "length", 1.5, "m"), p("height", "Height", "length", 1.3, "m"), p("glazing", "Glazing", "text", "Double")], instanceParameters: [p("sill", "Sill", "length", 0.9, "m")], host: "wall", metadata: { discipline: "Architecture" } },
  { id: "mep-air-handler", category: "mep-equipment", name: "Air Handling Equipment", description: "MEP equipment with power and service data.", types: ["AHU", "Fan coil", "Heat pump"], typeParameters: [p("ratedPowerKw", "Rated power", "number", 5, "kW"), p("serviceClearance", "Service clearance", "length", 0.9, "m")], instanceParameters: [p("assetTag", "Asset tag", "text", "AHU-001")], host: "level", metadata: { discipline: "Mechanical", review: "Required" } },
  { id: "mep-fixture", category: "mep-fixture", name: "MEP Fixture", description: "Hosted plumbing, electrical, or terminal fixture.", types: ["Plumbing fixture", "Light", "Diffuser"], typeParameters: [p("width", "Width", "length", 0.3, "m"), p("depth", "Depth", "length", 0.3, "m")], instanceParameters: [p("assetTag", "Asset tag", "text", "FX-001")], host: "ceiling", metadata: { discipline: "MEP", review: "Required" } },
];
export function familyForId(id?: string) { return FAMILY_LIBRARY.find((family) => family.id === id); }
export function familyForDraftKind(kind: DraftElementKind) { return FAMILY_LIBRARY.filter((family) => family.category === kind); }
export function familyForMepKind(kind: MepElementKind) { const category = kind === "equipment" ? "mep-equipment" : kind === "fixture" ? "mep-fixture" : undefined; return category ? FAMILY_LIBRARY.filter((family) => family.category === category) : []; }
export function familyMetadata(family: FamilyDefinition, type = family.types[0]): ParametricFamilyMetadata { return { libraryId: family.id, family: family.name, type, typeParameters: Object.fromEntries(family.typeParameters.map((item) => [item.key, item.defaultValue])), instanceParameters: Object.fromEntries(family.instanceParameters.map((item) => [item.key, item.defaultValue])), metadata: family.metadata }; }
