import { useState, type ChangeEvent } from "react";
import { Link } from "react-router-dom";
import { Badge, Button, Card, Input, Select } from "../components/ui";
import { exportIfcMeshObj, exportIfcRoundTrip, importIfcGeometry, type IfcDocument } from "../lib/ifcGeometry";
import { inspectBimGeometry, validateIds, type BimValidationReport } from "../lib/bimValidation";
import { constrainedSurveySurface, importGeoTiffDem, importLas, importSurveyCsv, routeSurfaceDrainage, transformSurveyPoint, type SurveyConstraints, type SurveyImport, type SurveySurface } from "../lib/surveyExchange";
import { advancedCivilCsv, analyzeAdvancedCivil, exampleAdvancedAlignment, parseAdvancedAlignment, type AdvancedCivilReport } from "../lib/civilAlignment";
import { inspectGeometryScene, type GeometryScene } from "../lib/meshGeometry";

const textareaClass = "min-h-40 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs text-slate-100";
function download(name: string, content: string, type = "application/json") { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement("a"); link.href = url; link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function parseConstraints(text: string): SurveyConstraints { if (text.length > 50000) throw new Error("Constraint JSON limit is 50 KB."); const value: unknown = JSON.parse(text); if (!value || typeof value !== "object" || !("breaklines" in value) || !("holes" in value) || !Array.isArray(value.breaklines) || !Array.isArray(value.holes) || ![...value.breaklines, ...value.holes].every(r => Array.isArray(r) && r.every(i => typeof i === "number"))) throw new Error("Constraints require breaklines and holes arrays of zero-based point indices."); return value as SurveyConstraints; }
function Plan({ lines }: { lines: number[][] }) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const line of lines) for (let i = 0; i < line.length; i += 2) { minX = Math.min(minX, line[i]); maxX = Math.max(maxX, line[i]); minY = Math.min(minY, line[i + 1]); maxY = Math.max(maxY, line[i + 1]); }
  if (!Number.isFinite(minX)) return null;
  const scale = 560 / Math.max(maxX - minX, maxY - minY, 1), path = (line: number[]) => line.reduce<string>((s, value, i) => i % 2 ? `${s},${580 - (value - minY) * scale} ` : `${s}${20 + (value - minX) * scale}`, "");
  return <svg role="img" aria-label="Plan projection in source horizontal coordinates" viewBox="0 0 600 600" className="max-h-96 w-full rounded-xl bg-slate-950">{lines.slice(0, 2000).map((line, i) => <polyline key={i} points={path(line)} fill="none" stroke="#67e8f9" strokeWidth="1" />)}</svg>;
}
function Findings({ report }: { report: BimValidationReport }) { return <div className="space-y-2"><Badge tone={report.status === "fail" ? "rose" : report.status === "incomplete" ? "amber" : "emerald"}>{report.status} · {report.checkedProducts} checked products</Badge><p className="text-xs text-slate-400">Implementation subset report; certification is not asserted. Showing up to 200 of {report.findings.length} findings.</p><ul className="max-h-80 space-y-1 overflow-auto text-xs">{report.findings.slice(0, 200).map((finding, i) => <li key={i} className="rounded bg-slate-950 p-2"><strong>{finding.status}: {finding.specification}</strong> {finding.globalId && <code>{finding.globalId}</code>} — {finding.message}</li>)}</ul></div>; }

function geometryScene(meshes: GeometryScene["meshes"], warnings: string[]): GeometryScene {
  let minX = Infinity, minY = Infinity, minZ = Infinity, maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity, triangleCount = 0;
  for (const mesh of meshes) { triangleCount += mesh.indices.length / 3; for (let i = 0; i < mesh.positions.length; i += 3) { minX = Math.min(minX, mesh.positions[i]); maxX = Math.max(maxX, mesh.positions[i]); minY = Math.min(minY, mesh.positions[i + 1]); maxY = Math.max(maxY, mesh.positions[i + 1]); minZ = Math.min(minZ, mesh.positions[i + 2]); maxZ = Math.max(maxZ, mesh.positions[i + 2]); } }
  if (!meshes.length || triangleCount < 1 || triangleCount > 400000) throw new Error("Geometry scene export needs 1–400,000 supported triangles.");
  const target: [number, number, number] = [(minX + maxX) / 2, (minY + maxY) / 2, (minZ + maxZ) / 2], span = Math.max(maxX - minX, maxY - minY, maxZ - minZ, 1);
  return inspectGeometryScene({ version: 1, units: "m", meshes, camera: { target, position: [target[0] + span, target[1] + span, target[2] + span], up: [0, 1, 0], fov: 50 }, warnings });
}
function ifcScene(document: IfcDocument): GeometryScene { return geometryScene(document.products.flatMap(p => p.meshes.map((m, i) => ({ id: `${p.globalId}:${i}`, sourceId: p.globalId, positions: m.vertices.map((v, j) => j % 3 === 1 ? m.vertices[j + 1] : j % 3 === 2 ? -m.vertices[j - 1] : v), indices: m.triangles, material: { color: [.7, .75, .8] as [number, number, number], emission: [0, 0, 0] as [number, number, number], model: "diffuse" as const, ior: 1.5 } }))), [...document.issues, ...document.products.flatMap(p => p.issues.map(issue => `${p.globalId}: ${issue}`)), "IFC Z-up converted to Y-up: x=X, y=Z, z=-Y."]); }

export function ExchangeWorkbench() {
  const [tab, setTab] = useState<"bim" | "survey" | "civil">("bim"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [ifc, setIfc] = useState<IfcDocument>(), [idsText, setIdsText] = useState(""), [bimReport, setBimReport] = useState<BimValidationReport>(), [selected, setSelected] = useState(""), [names, setNames] = useState<Record<string, string>>({});
  const [survey, setSurvey] = useState<SurveyImport>(), [surface, setSurface] = useState<SurveySurface>(), [fromCrs, setFromCrs] = useState("LOCAL"), [toCrs, setToCrs] = useState("LOCAL"), [constraints, setConstraints] = useState('{"breaklines": [], "holes": []}');
  const [alignment, setAlignment] = useState(JSON.stringify(exampleAdvancedAlignment, null, 2)), [civilReport, setCivilReport] = useState<AdvancedCivilReport>();
  const perform = (action: () => void) => { setError(""); try { action(); } catch (e) { setError(e instanceof Error ? e.message : "Operation failed."); } };
  async function importFile(event: ChangeEvent<HTMLInputElement>, kind: "ifc" | "ids" | "survey") {
    const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; if (!file) return; setBusy(true); setError("");
    try {
      const limit = kind === "ifc" ? 20000000 : kind === "ids" ? 2000000 : 64000000; if (file.size > limit) throw new Error(`File exceeds ${limit / 1000000} MB limit.`);
      if (kind === "ifc") { const document = importIfcGeometry(await file.text()); setIfc(document); setBimReport(inspectBimGeometry(document)); setNames({}); setSelected(document.products[0]?.globalId ?? ""); }
      else if (kind === "ids") { setIdsText(await file.text()); setBimReport(undefined); }
      else { const imported = /\.las$/i.test(file.name) ? importLas(await file.arrayBuffer()) : /\.tiff?$/i.test(file.name) ? importGeoTiffDem(await file.arrayBuffer()) : importSurveyCsv(await file.text()); setSurvey(imported); setSurface(undefined); setCivilReport(undefined); setFromCrs(imported.crs ?? "LOCAL"); setToCrs(imported.crs ?? "LOCAL"); }
    } catch (e) { setError(e instanceof Error ? e.message : "Import failed."); } finally { setBusy(false); }
  }
  const product = ifc?.products.find(p => p.globalId === selected);
  const renamedDocument = ifc ? { ...ifc, products: ifc.products.map(p => names[p.globalId] === undefined ? p : { ...p, name: names[p.globalId], attributes: { ...p.attributes, Name: names[p.globalId] } }) } : undefined;
  const meshLines: number[][] = []; if (ifc && tab === "bim") outer: for (const p of ifc.products) for (const mesh of p.meshes) for (let i = 0; i < mesh.triangles.length; i += 3) { const indices = mesh.triangles.slice(i, i + 3); indices.push(indices[0]); meshLines.push(indices.flatMap(index => [mesh.vertices[index * 3], mesh.vertices[index * 3 + 1]])); if (meshLines.length >= 2000) break outer; }
  const surfaceLines = surface?.triangles.slice(0, 2000).map(t => [...t, t[0]].flatMap(i => [surface.points[i].x, surface.points[i].z])) ?? [];
  return <main className="mx-auto max-w-6xl space-y-5 p-4 md:p-8">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">BIM and survey exchange</h1><p className="text-sm text-slate-400">Bounded source geometry, information requirements, survey surfaces and civil alignment studies.</p></div><Link to="/dashboard" className="text-sm text-cyan-300">Projects</Link></div>
    <div className="flex gap-2">{(["bim", "survey", "civil"] as const).map(value => <Button key={value} variant={tab === value ? "primary" : "secondary"} onClick={() => { setTab(value); setError(""); }}>{value === "bim" ? "IFC / IDS" : value === "survey" ? "Survey / DEM" : "Civil alignment"}</Button>)}</div>
    {error && <p role="alert" className="rounded-xl border border-rose-800 bg-rose-950/40 p-3 text-rose-200">{error}</p>}
    {tab === "bim" && <Card className="space-y-4 p-5">
      <h2 className="text-lg font-semibold">IFC geometry and stable source exchange</h2><p className="text-sm text-slate-400">IFC2X3/IFC4 STEP: local placements, rectangular/circular/simple polygon extrusion, triangle sets and polygonal BRep faces. Source geometry and GlobalIds remain in IFC exports. Openings, Boolean and mapped geometry are reported as unsupported.</p>
      <label className="block text-sm">Import IFC (20 MB)<input className="mt-2 block w-full" type="file" accept=".ifc" disabled={busy} onChange={event => { void importFile(event, "ifc"); }} /></label>
      {ifc && <><p>{ifc.schema} · {ifc.products.length} products · {ifc.unitScale} metres per source unit</p><Plan lines={meshLines} /><p className="text-xs text-slate-400">Plan projection shows up to 2000 supported triangles; full supported meshes are included in OBJ export.</p>
        <div className="grid gap-3 md:grid-cols-2"><Select label="Product to rename" value={selected} onChange={event => setSelected(event.target.value)}>{ifc.products.slice(0, 500).map(p => <option key={p.stepId} value={p.globalId}>{p.type} · {p.name || p.globalId}</option>)}</Select>{product && <Input label="Exported name" value={names[product.globalId] ?? product.name} maxLength={1024} onChange={event => { setNames({ ...names, [product.globalId]: event.target.value }); setBimReport(undefined); }} />}</div>
        {product && <pre className="max-h-40 overflow-auto rounded bg-slate-950 p-3 text-xs">{JSON.stringify({ globalId: product.globalId, attributes: product.attributes, properties: product.properties, issues: product.issues }, null, 2)}</pre>}
        <div className="flex flex-wrap gap-2"><Button onClick={() => perform(() => download("roundtrip.ifc", exportIfcRoundTrip(ifc, names), "application/x-step"))}>Export source IFC with names</Button><Button variant="secondary" onClick={() => perform(() => download("supported-geometry.obj", exportIfcMeshObj(ifc), "text/plain"))}>Export supported OBJ</Button><Button variant="secondary" onClick={() => download("ifc-metadata.json", JSON.stringify({ schema: ifc.schema, products: renamedDocument!.products.map(({ meshes, ...p }) => ({ ...p, meshParts: meshes.length })), issues: ifc.issues }, null, 2))}>Export metadata</Button></div>
        <Button variant="secondary" onClick={() => perform(() => download("geometry-scene.json", JSON.stringify(ifcScene(ifc))))}>Export geometry scene for clash / rendering workbench</Button>
        <h3 className="font-semibold">IDS requirements</h3><p className="text-xs text-slate-400">Literal entity, attribute and untyped single-value property facets are supported. Exact entity classes are checked; subtype inheritance, restrictions, classification, materials and parts facets produce an incomplete report. Name checks use the current exported names.</p><input aria-label="Import IDS XML" type="file" accept=".ids,.xml" disabled={busy} onChange={event => { void importFile(event, "ids"); }} /><textarea aria-label="IDS XML" className={textareaClass} value={idsText} onChange={event => { setIdsText(event.target.value); setBimReport(undefined); }} />
        <div className="flex flex-wrap gap-2"><Button disabled={!idsText} onClick={() => perform(() => setBimReport(validateIds(renamedDocument!, idsText)))}>Check supported IDS requirements</Button><Button variant="secondary" onClick={() => setBimReport(inspectBimGeometry(ifc))}>Geometry coverage</Button>{bimReport && <Button variant="secondary" onClick={() => download("bim-validation.json", JSON.stringify(bimReport, null, 2))}>Export report</Button>}</div>{bimReport && <Findings report={bimReport} />}
      </>}
    </Card>}
    {tab === "survey" && <Card className="space-y-4 p-5"><h2 className="text-lg font-semibold">Survey reprojection and constrained terrain</h2><p className="text-sm text-slate-400">CSV easting,northing,elevation; uncompressed LAS 1.1–1.4; classic uncompressed single-band north-up GeoTIFF DEM. Binary inputs are sampled to at most 2000 points. Elevation must be metres; vertical datums are unchanged.</p><input aria-label="Import survey" type="file" accept=".csv,.txt,.las,.tif,.tiff" disabled={busy} onChange={event => { void importFile(event, "survey"); }} />
      {survey && <><p>{survey.points.length} sampled points from {survey.originalCount} records/cells.</p><ul className="text-xs text-amber-200">{survey.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul><div className="grid gap-3 md:grid-cols-2"><Input label="Source CRS (LOCAL or EPSG code)" value={fromCrs} onChange={event => { setFromCrs(event.target.value); setSurface(undefined); setCivilReport(undefined); }} /><Input label="Target CRS (LOCAL or EPSG code)" value={toCrs} onChange={event => { setToCrs(event.target.value); setSurface(undefined); setCivilReport(undefined); }} /></div><p className="text-xs text-slate-400">WGS84 longitude/latitude EPSG:4326, Web Mercator EPSG:3857, WGS84 UTM EPSG:32601–32660 / 32701–32760. LOCAL retains surveyed metre coordinates; no georeferencing is inferred. Terrain and civil work require projected metre coordinates.</p>
        <label className="block text-sm">Breaklines and terrain holes (zero-based indices into imported points)<textarea className={`${textareaClass} mt-2`} value={constraints} onChange={event => { setConstraints(event.target.value); setSurface(undefined); setCivilReport(undefined); }} /></label><Button onClick={() => perform(() => { const sourceCrs = fromCrs.trim().toUpperCase(), targetCrs = toCrs.trim().toUpperCase(); if (targetCrs === "EPSG:4326") throw new Error("TIN/civil operations need a projected metre CRS."); if ((sourceCrs === "LOCAL") !== (targetCrs === "LOCAL")) throw new Error("LOCAL cannot be transformed to a georeferenced CRS without survey control."); const points = sourceCrs === "LOCAL" ? survey.points : survey.points.map(p => transformSurveyPoint(p, sourceCrs, targetCrs)); setSurface(constrainedSurveySurface(points, parseConstraints(constraints))); setFromCrs(sourceCrs); setToCrs(targetCrs); setCivilReport(undefined); })}>Transform and build constrained surface</Button>
        {surface && <><Plan lines={surfaceLines} /><p className="text-xs text-slate-400">{surface.triangles.length} triangles; plan projection shows up to 2000. Constraints and holes refer to the complete point list.</p><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => download("survey-surface.json", JSON.stringify({ crs: toCrs, ...surface }, null, 2))}>Export transformed surface</Button><Button variant="secondary" onClick={() => perform(() => download("surface-drainage.json", JSON.stringify({ crs: toCrs, ...routeSurfaceDrainage(surface), limitation: "Steepest mesh vertex descent; sinks retained; no hydraulic or pit-fill model." }, null, 2)))}>Export drainage routes</Button></div></>}
        {surface && <Button variant="secondary" onClick={() => perform(() => download("geometry-scene.json", JSON.stringify(geometryScene([{ id: "survey-surface", sourceId: "survey-surface", positions: surface.points.flatMap(p => [p.x, p.elevationM, -p.z]), indices: surface.triangles.flat(), material: { color: [.45, .55, .3], emission: [0, 0, 0], model: "diffuse", ior: 1.5 } }], [...surface.warnings, `Projected CRS ${toCrs}; y is metre elevation and z is negative northing.`]))))}>Export terrain geometry scene</Button>}
      </>}
    </Card>}
    {tab === "civil" && <Card className="space-y-4 p-5"><h2 className="text-lg font-semibold">Circular / clothoid / parabolic alignment</h2><p className="text-sm text-slate-400">JSON defines connected horizontal segments, continuous parabolic vertical curves and superelevation stations. Signed arc radius and curvature turn left when positive. Positive superelevation raises the left edge. Survey surface: {surface ? `${surface.triangles.length} triangles in ${toCrs}` : "none; geometry and profile only"}.</p><textarea aria-label="Civil alignment JSON in metres" className={`${textareaClass} min-h-96`} value={alignment} onChange={event => { setAlignment(event.target.value); setCivilReport(undefined); }} /><Button onClick={() => perform(() => setCivilReport(analyzeAdvancedCivil(parseAdvancedAlignment(alignment), surface)))}>Calculate alignment and earthworks</Button>
      {civilReport && <><Plan lines={[civilReport.stations.flatMap(s => [s.x, s.z])]} /><p>{civilReport.lengthM.toFixed(2)} m · {civilReport.stations.length} stations · cut {civilReport.cutM3.toFixed(2)} m³ · fill {civilReport.fillM3.toFixed(2)} m³ · quantified {civilReport.quantifiedLengthM.toFixed(2)} m</p><ul className="text-xs text-amber-200">{civilReport.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => download("civil-alignment-report.json", JSON.stringify({ crs: surface ? toCrs : "LOCAL", alignment: parseAdvancedAlignment(alignment), ...civilReport }, null, 2))}>Export alignment / sections JSON</Button><Button variant="secondary" onClick={() => download("civil-stations.csv", advancedCivilCsv(civilReport), "text/csv")}>Export station CSV</Button></div></>}
    </Card>}
  </main>;
}
