import { useMemo, useRef, useState, type ChangeEvent } from "react";
import { Link } from "react-router-dom";
import { Badge, Button, Card, Input, Select } from "../components/ui";
import { ProjectWorkspacePanel } from "../components/ProjectWorkspacePanel";
import { ProjectJobsPanel } from "../components/ProjectJobsPanel";
import type { ProjectDetail } from "../types";
import { buildIfcStep } from "../lib/bim";
import { inspectIfcEngineeringDeclaration } from "../lib/ifcEngineeringProvenance";
import { exportIfcMeshObj, exportIfcRoundTrip, importIfcGeometry, type IfcDocument } from "../lib/ifcGeometry";
import { inspectBimGeometry, validateIds, type BimValidationReport } from "../lib/bimValidation";
import { exportIfcPropertyEdits } from "../lib/ifcPropertyAuthoring";
import { constrainedSurveySurface, importGeoTiffDem, importLas, importSurveyCsv, inspectSurveyCoordinateMetadata, prepareSurveyForTerrain, routeSurfaceDrainage, transformSurveyPoint, type SurveyConstraints, type SurveyImport, type SurveySurface } from "../lib/surveyExchange";
import { advancedCivilCsv, analyzeAdvancedCivil, exampleAdvancedAlignment, parseAdvancedAlignment, type AdvancedCivilReport } from "../lib/civilAlignment";
import { inspectGeometryScene, type GeometryScene } from "../lib/meshGeometry";

const textareaClass = "min-h-40 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs text-slate-100";
type ExchangeTab = "bim" | "survey" | "civil";
type BimReportKind = "geometry" | "ids";
interface SurveyProjectFrame { projectId: string; projectCrs: string; originEastingM: number; originNorthingM: number; coordinates: "local" | "projected" }
interface ExchangeWorkspaceState {
  version: 3; tab: ExchangeTab; ifcSource: string | null; idsText: string; names: Record<string, string>; selected: string; propertyEditsText: string;
  survey: SurveyImport | null; surveyProjectFrame: SurveyProjectFrame | null; fromCrs: string; toCrs: string; constraints: string; surveyDeclarationText: string;
  surfaceCalculated: boolean; alignment: string; civilCalculated: boolean; bimReportKind: BimReportKind | null;
}
const isRecord = (value: unknown): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value);
const finite = (value: unknown): value is number => typeof value === "number" && Number.isFinite(value);
const emptyPropertyEdits = '{"version":1,"edits":[]}';
const emptySurveyDeclaration = JSON.stringify({ version: 1, horizontalCrs: "", horizontalUnit: "", axisOrder: "", elevationUnit: "", verticalDatum: "", source: "" }, null, 2);
function editedIfc(document: IfcDocument, editText: string, names: Record<string, string>): IfcDocument {
  const edited = exportIfcPropertyEdits(document, JSON.parse(editText) as unknown);
  const authored = edited === document.source ? document : importIfcGeometry(edited);
  const renamed = exportIfcRoundTrip(authored, names);
  return renamed === authored.source ? authored : importIfcGeometry(renamed);
}
function boundedText(value: unknown, maximum: number, label: string): string { if (typeof value !== "string" || value.length > maximum) throw new Error(`${label} exceeds its saved input limit.`); return value; }
function surveyState(value: unknown): SurveyImport {
  if (!isRecord(value) || !Array.isArray(value.points) || value.points.length < 3 || value.points.length > 2000 || !finite(value.originalCount) || !Number.isSafeInteger(value.originalCount) || value.originalCount < value.points.length || !Array.isArray(value.warnings) || value.warnings.length > 100) throw new Error("Saved survey requires 3–2000 points and bounded source metadata.");
  const points = value.points.map((p): SurveyImport["points"][number] => {
    if (!isRecord(p) || !finite(p.x) || !finite(p.z) || !finite(p.elevationM) || Math.abs(p.x) > 1e8 || Math.abs(p.z) > 1e8 || Math.abs(p.elevationM) > 1e5) throw new Error("Saved survey has invalid coordinates.");
    const point = { x: p.x, z: p.z, elevationM: p.elevationM }, classification = p.classification;
    if (classification === undefined) return point;
    if (!finite(classification) || !Number.isInteger(classification) || classification < 0 || classification > 255) throw new Error("Saved survey classification is invalid.");
    return { ...point, classification };
  });
  return { points, originalCount: Number(value.originalCount), warnings: value.warnings.map(w => boundedText(w, 2000, "Survey warning")), ...(value.crs === undefined ? {} : { crs: boundedText(value.crs, 100, "Survey CRS") }), ...(value.coordinateMetadata === undefined ? {} : { coordinateMetadata: inspectSurveyCoordinateMetadata(value.coordinateMetadata) }) };
}
function projectFrameState(value: unknown): SurveyProjectFrame | null {
  if (value === null) return null;
  if (!isRecord(value) || !finite(value.originEastingM) || !finite(value.originNorthingM) || Math.abs(value.originEastingM) > 1e8 || Math.abs(value.originNorthingM) > 1e8 || value.coordinates !== "local" && value.coordinates !== "projected") throw new Error("Saved project survey frame is invalid.");
  return { projectId: boundedText(value.projectId, 200, "Source project"), projectCrs: boundedText(value.projectCrs, 100, "Project CRS"), originEastingM: value.originEastingM, originNorthingM: value.originNorthingM, coordinates: value.coordinates };
}
function buildWorkspaceSurface(survey: SurveyImport, from: string, to: string, constraints: string, declarationText: string, frame: SurveyProjectFrame | null): SurveySurface {
  const prepared = prepareSurveyForTerrain(survey, JSON.parse(boundedText(declarationText, 10000, "Survey coordinate declaration")) as unknown);
  if (frame && (prepared.provenance.declaration.horizontalUnit !== "m" || prepared.provenance.declaration.elevationUnit !== "m")) throw new Error("Imported project terrain already uses metres. Its coordinate units cannot be relabelled.");
  const source = from.trim().toUpperCase(), target = to.trim().toUpperCase();
  if (source !== prepared.crs.trim().toUpperCase()) throw new Error("Source CRS must match the reviewed survey coordinate declaration.");
  if (target === "EPSG:4326") throw new Error("TIN/civil operations need a projected metre CRS.");
  if ((source === "LOCAL") !== (target === "LOCAL")) throw new Error("LOCAL cannot be transformed to a georeferenced CRS without survey control.");
  const surface = constrainedSurveySurface(source === "LOCAL" ? prepared.points : prepared.points.map(p => transformSurveyPoint(p, source, target)), parseConstraints(constraints));
  return { ...surface, warnings: [...prepared.warnings, ...surface.warnings].slice(0, 100) };
}
function restoreWorkspace(value: unknown): { state: ExchangeWorkspaceState; ifc?: IfcDocument; surface?: SurveySurface; bimReport?: BimValidationReport; civilReport?: AdvancedCivilReport } {
  if (!isRecord(value) || value.version !== 1 && value.version !== 2 && value.version !== 3 || value.tab !== "bim" && value.tab !== "survey" && value.tab !== "civil" || typeof value.surfaceCalculated !== "boolean" || typeof value.civilCalculated !== "boolean" || value.bimReportKind !== null && value.bimReportKind !== "geometry" && value.bimReportKind !== "ids" || !isRecord(value.names) || Object.keys(value.names).length > 10000) throw new Error("Unsupported saved exchange workspace.");
  const ifcSource = value.ifcSource === null ? null : boundedText(value.ifcSource, 20000000, "IFC source"), ifc = ifcSource === null ? undefined : importIfcGeometry(ifcSource);
  const names: Record<string, string> = Object.create(null) as Record<string, string>, ids = new Set(ifc?.products.map(p => p.globalId));
  for (const [key, name] of Object.entries(value.names)) { if (!ids.has(key) || ["__proto__", "constructor", "prototype"].includes(key)) throw new Error("Saved names must refer to imported product identifiers."); const next = boundedText(name, 1024, "Product name"); if (/[\u0000-\u001f\u007f]/.test(next)) throw new Error("Saved product names contain control characters."); names[key] = next; }
  const selected = boundedText(value.selected, 200, "Selected product"); if (selected && !ids.has(selected)) throw new Error("Saved selected product is unavailable.");
  const state: ExchangeWorkspaceState = { version: 3, tab: value.tab, ifcSource, names, selected, propertyEditsText: value.version === 1 ? emptyPropertyEdits : boundedText(value.propertyEditsText, 250000, "Property edit draft"), idsText: boundedText(value.idsText, 2000000, "IDS XML"), survey: value.survey === null ? null : surveyState(value.survey), surveyProjectFrame: projectFrameState(value.surveyProjectFrame), fromCrs: boundedText(value.fromCrs, 100, "Source CRS"), toCrs: boundedText(value.toCrs, 100, "Target CRS"), constraints: boundedText(value.constraints, 50000, "Constraints"), surveyDeclarationText: value.version === 3 ? boundedText(value.surveyDeclarationText, 10000, "Survey coordinate declaration") : emptySurveyDeclaration, alignment: boundedText(value.alignment, 100000, "Alignment"), surfaceCalculated: value.version === 3 && value.surfaceCalculated, civilCalculated: value.version === 3 && value.civilCalculated, bimReportKind: value.bimReportKind };
  if (value.version !== 3 && state.survey && (value.surfaceCalculated || value.civilCalculated)) state.survey.warnings = [...state.survey.warnings.slice(0, 99), "Legacy survey inputs retained. Declare coordinate units, axes and the unchanged vertical datum before rebuilding terrain/civil results."];
  if (state.surveyProjectFrame && !state.survey) throw new Error("Saved project frame requires a survey.");
  if (state.surfaceCalculated && !state.survey) throw new Error("Saved surface requires survey inputs.");
  const surface = state.surfaceCalculated ? buildWorkspaceSurface(state.survey!, state.fromCrs, state.toCrs, state.constraints, state.surveyDeclarationText, state.surveyProjectFrame) : undefined;
  if (state.bimReportKind && !ifc) throw new Error("Saved BIM report requires IFC source.");
  if (ifc) exportIfcRoundTrip(ifc, names); // Validate duplicate identifiers/rename ambiguity before committing restored state.
  const renamed = state.bimReportKind === "ids" && ifc ? editedIfc(ifc, state.propertyEditsText, names) : undefined;
  const bimReport = state.bimReportKind === "geometry" ? inspectBimGeometry(ifc!) : state.bimReportKind === "ids" ? validateIds(renamed!, state.idsText) : undefined;
  const civilReport = state.civilCalculated ? analyzeAdvancedCivil(parseAdvancedAlignment(state.alignment), surface) : undefined;
  return { state, ifc, surface, bimReport, civilReport };
}
function download(name: string, content: string, type = "application/json") { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement("a"); link.href = url; link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function parseConstraints(text: string): SurveyConstraints { if (text.length > 50000) throw new Error("Constraint JSON limit is 50 KB."); const value: unknown = JSON.parse(text); if (!value || typeof value !== "object" || !("breaklines" in value) || !("holes" in value) || !Array.isArray(value.breaklines) || !Array.isArray(value.holes) || ![...value.breaklines, ...value.holes].every(r => Array.isArray(r) && r.every(i => typeof i === "number"))) throw new Error("Constraints require breaklines and holes arrays of zero-based point indices."); return value as SurveyConstraints; }
function Plan({ lines }: { lines: number[][] }) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const line of lines) for (let i = 0; i < line.length; i += 2) { minX = Math.min(minX, line[i]); maxX = Math.max(maxX, line[i]); minY = Math.min(minY, line[i + 1]); maxY = Math.max(maxY, line[i + 1]); }
  if (!Number.isFinite(minX)) return null;
  const scale = 560 / Math.max(maxX - minX, maxY - minY, 1), path = (line: number[]) => line.reduce<string>((s, value, i) => i % 2 ? `${s},${580 - (value - minY) * scale} ` : `${s}${20 + (value - minX) * scale}`, "");
  return <svg role="img" aria-label="Plan projection in source horizontal coordinates" viewBox="0 0 600 600" className="max-h-96 w-full rounded-xl bg-slate-950">{lines.slice(0, 2000).map((line, i) => <polyline key={i} points={path(line)} fill="none" stroke="#67e8f9" strokeWidth="1" />)}</svg>;
}
function Findings({ report }: { report: BimValidationReport }) { return <div className="space-y-2"><Badge tone={report.status === "fail" ? "rose" : report.status === "incomplete" ? "amber" : "emerald"}>{report.status} · {report.checkedProducts} checked products</Badge><p className="text-xs text-slate-400">Implementation subset report; certification is not asserted. Showing up to 200 of {report.findings.length} findings.</p><ul className="max-h-80 space-y-1 overflow-auto text-xs">{report.findings.slice(0, 200).map((finding, i) => <li key={i} className="rounded bg-slate-950 p-2"><strong>{finding.status}: {finding.specification}</strong> {finding.globalId && <code>{finding.globalId}</code>} — {finding.message}</li>)}</ul></div>; }

function geometryScene(meshes: GeometryScene["meshes"], warnings: string[]): GeometryScene {
  let minX = Infinity, minY = Infinity, minZ = Infinity, maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity, triangleCount = 0;
  for (const mesh of meshes) { triangleCount += mesh.indices.length / 3; for (let i = 0; i < mesh.positions.length; i += 3) { minX = Math.min(minX, mesh.positions[i]); maxX = Math.max(maxX, mesh.positions[i]); minY = Math.min(minY, mesh.positions[i + 1]); maxY = Math.max(maxY, mesh.positions[i + 1]); minZ = Math.min(minZ, mesh.positions[i + 2]); maxZ = Math.max(maxZ, mesh.positions[i + 2]); } }
  if (!meshes.length || triangleCount < 1 || triangleCount > 400000) throw new Error("Geometry scene export needs 1–400,000 supported triangles.");
  const target: [number, number, number] = [(minX + maxX) / 2, (minY + maxY) / 2, (minZ + maxZ) / 2], span = Math.max(maxX - minX, maxY - minY, maxZ - minZ, 1);
  return inspectGeometryScene({ version: 1, units: "m", meshes, camera: { target, position: [target[0] + span, target[1] + span, target[2] + span], up: [0, 1, 0], fov: 50 }, warnings });
}
function ifcScene(document: IfcDocument): GeometryScene { return geometryScene(document.products.flatMap(p => p.meshes.map((m, i) => ({ id: `${p.globalId}:${i}`, sourceId: p.globalId, positions: m.vertices.map((v, j) => j % 3 === 1 ? m.vertices[j + 1] : j % 3 === 2 ? -m.vertices[j - 1] : v), indices: m.triangles, material: { color: [.7, .75, .8] as [number, number, number], emission: [0, 0, 0] as [number, number, number], model: "diffuse" as const, ior: 1.5 } }))), [...document.issues, ...document.products.flatMap(p => p.issues.map(issue => `${p.globalId}: ${issue}`)), "IFC Z-up converted to Y-up: x=X, y=Z, z=-Y."]); }

export function ExchangeWorkbench() {
  const [tab, setTab] = useState<ExchangeTab>("bim"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [ifc, setIfc] = useState<IfcDocument>(), [idsText, setIdsText] = useState(""), [bimReport, setBimReport] = useState<BimValidationReport>(), [selected, setSelected] = useState(""), [names, setNames] = useState<Record<string, string>>(() => Object.create(null) as Record<string, string>);
  const [survey, setSurvey] = useState<SurveyImport>(), [surface, setSurface] = useState<SurveySurface>(), [fromCrs, setFromCrs] = useState("LOCAL"), [toCrs, setToCrs] = useState("LOCAL"), [constraints, setConstraints] = useState('{"breaklines": [], "holes": []}');
  const [alignment, setAlignment] = useState(JSON.stringify(exampleAdvancedAlignment, null, 2)), [civilReport, setCivilReport] = useState<AdvancedCivilReport>();
  const [bimReportKind, setBimReportKind] = useState<BimReportKind | null>(null), [surveyProjectFrame, setSurveyProjectFrame] = useState<SurveyProjectFrame | null>(null);
  const [propertyEditsText, setPropertyEditsText] = useState(emptyPropertyEdits);
  const [surveyDeclarationText, setSurveyDeclarationText] = useState(emptySurveyDeclaration);
  const importGeneration = useRef(0);
  const workspace = useMemo<ExchangeWorkspaceState>(() => ({ version: 3, tab, ifcSource: ifc?.source ?? null, idsText, names, selected, propertyEditsText, survey: survey ?? null, surveyProjectFrame, fromCrs, toCrs, constraints, surveyDeclarationText, surfaceCalculated: !!surface, alignment, civilCalculated: !!civilReport, bimReportKind }), [tab, ifc, idsText, names, selected, propertyEditsText, survey, surveyProjectFrame, fromCrs, toCrs, constraints, surveyDeclarationText, surface, alignment, civilReport, bimReportKind]);
  const applyWorkspace = (value: unknown) => {
    const restored = restoreWorkspace(value), state = restored.state;
    importGeneration.current++; setBusy(false);
    setTab(state.tab); setIfc(restored.ifc); setIdsText(state.idsText); setNames(state.names); setSelected(state.selected || restored.ifc?.products[0]?.globalId || "");
    setPropertyEditsText(state.propertyEditsText);
    setSurveyDeclarationText(state.surveyDeclarationText);
    setSurvey(state.survey ?? undefined); setSurveyProjectFrame(state.surveyProjectFrame); setFromCrs(state.fromCrs); setToCrs(state.toCrs); setConstraints(state.constraints); setSurface(restored.surface);
    setAlignment(state.alignment); setCivilReport(restored.civilReport); setBimReport(restored.bimReport); setBimReportKind(state.bimReportKind); setError("");
  };
  const importProject = (project: ProjectDetail) => {
    if (!project.design) throw new Error("This project has no saved design to import.");
    const source = buildIfcStep(project.design), terrain = project.design.infra?.terrain ?? project.design.community?.terrain;
    let nextSurvey: SurveyImport | null = null, frame: SurveyProjectFrame | null = null, crs = "LOCAL";
    if (terrain?.source === "survey" && terrain.samples?.length) {
      const originalCrs = terrain.projectCrs?.trim().toUpperCase() || "LOCAL", easting = terrain.localOriginEasting ?? 0, northing = terrain.localOriginNorthing ?? 0;
      if (!finite(easting) || !finite(northing) || Math.abs(easting) > 1e8 || Math.abs(northing) > 1e8) throw new Error("Project terrain survey origin is invalid.");
      const epsg = /^EPSG:(\d+)$/.exec(originalCrs), code = Number(epsg?.[1]), projected = code === 3857 || code >= 32601 && code <= 32660 || code >= 32701 && code <= 32760;
      crs = projected ? originalCrs : "LOCAL";
      frame = { projectId: project.id, projectCrs: originalCrs, originEastingM: easting, originNorthingM: northing, coordinates: projected ? "projected" : "local" };
      nextSurvey = surveyState({ points: terrain.samples.map(p => ({ x: p.x + (projected ? easting : 0), z: p.z + (projected ? northing : 0), elevationM: p.elevationM })), crs, originalCount: terrain.samples.length, warnings: [projected ? `Project survey origin explicitly added: easting ${easting} m, northing ${northing} m; stored local x/z become easting/northing in ${originalCrs}. No reprojection or vertical conversion performed.` : `Stored local project x/z coordinates retained. Project CRS metadata is ${originalCrs}; origin easting ${easting} m, northing ${northing} m is retained as metadata. No georeferencing, axis rotation or vertical conversion inferred.`, "Project terrain CRS is authored metadata; independently confirm metre units and model-axis alignment before geospatial use."] });
    }
    applyWorkspace({ version: 1, tab: "bim", ifcSource: source, idsText: "", names: {}, selected: "", survey: nextSurvey, surveyProjectFrame: frame, fromCrs: crs, toCrs: crs, constraints: '{"breaklines": [], "holes": []}', surfaceCalculated: false, alignment: JSON.stringify(exampleAdvancedAlignment, null, 2), civilCalculated: false, bimReportKind: "geometry" });
  };
  const perform = (action: () => void) => { setError(""); try { action(); } catch (e) { setError(e instanceof Error ? e.message : "Operation failed."); } };
  async function importFile(event: ChangeEvent<HTMLInputElement>, kind: "ifc" | "ids" | "survey") {
    const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; if (!file) return; const generation = ++importGeneration.current; setBusy(true); setError("");
    try {
      const limit = kind === "ifc" ? 20000000 : kind === "ids" ? 2000000 : 64000000; if (file.size > limit) throw new Error(`File exceeds ${limit / 1000000} MB limit.`);
      const binary = kind === "survey" && /\.(las|tiff?)$/i.test(file.name), content = binary ? await file.arrayBuffer() : await file.text();
      if (generation !== importGeneration.current) return;
      if (kind === "ifc") { const document = importIfcGeometry(content as string); setIfc(document); setBimReport(inspectBimGeometry(document)); setBimReportKind("geometry"); setNames(Object.create(null) as Record<string, string>); setPropertyEditsText(emptyPropertyEdits); setSelected(document.products[0]?.globalId ?? ""); }
      else if (kind === "ids") { setIdsText(content as string); setBimReport(undefined); setBimReportKind(null); }
      else { const imported = /\.las$/i.test(file.name) ? importLas(content as ArrayBuffer) : /\.tiff?$/i.test(file.name) ? importGeoTiffDem(content as ArrayBuffer) : importSurveyCsv(content as string); setSurvey(surveyState(imported)); setSurveyDeclarationText(emptySurveyDeclaration); setSurveyProjectFrame(null); setSurface(undefined); setCivilReport(undefined); setFromCrs(imported.crs ?? "LOCAL"); setToCrs(imported.crs ?? "LOCAL"); }
    } catch (e) { if (generation === importGeneration.current) setError(e instanceof Error ? e.message : "Import failed."); } finally { if (generation === importGeneration.current) setBusy(false); }
  }
  const product = ifc?.products.find(p => p.globalId === selected);
  const ifcDeclaration = useMemo(() => ifc ? inspectIfcEngineeringDeclaration(ifc) : null, [ifc]);
  const meshLines: number[][] = []; if (ifc && tab === "bim") outer: for (const p of ifc.products) for (const mesh of p.meshes) for (let i = 0; i < mesh.triangles.length; i += 3) { const indices = mesh.triangles.slice(i, i + 3); indices.push(indices[0]); meshLines.push(indices.flatMap(index => [mesh.vertices[index * 3], mesh.vertices[index * 3 + 1]])); if (meshLines.length >= 2000) break outer; }
  const surfaceLines = surface?.triangles.slice(0, 2000).map(t => [...t, t[0]].flatMap(i => [surface.points[i].x, surface.points[i].z])) ?? [];
  return <main className="mx-auto max-w-6xl space-y-5 p-4 md:p-8">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">BIM and survey exchange</h1><p className="text-sm text-slate-400">Bounded source geometry, information requirements, survey surfaces and civil alignment studies.</p></div><Link to="/dashboard" className="text-sm text-cyan-300">Projects</Link></div>
    <ProjectWorkspacePanel kind="exchange" payload={workspace} onRestore={applyWorkspace} onImportProject={importProject} />
    <ProjectJobsPanel workspaceKind="exchange" kinds={["dwg-to-dxf", "dxf-to-dwg"]} />
    <div className="flex gap-2">{(["bim", "survey", "civil"] as const).map(value => <Button key={value} variant={tab === value ? "primary" : "secondary"} onClick={() => { setTab(value); setError(""); }}>{value === "bim" ? "IFC / IDS" : value === "survey" ? "Survey / DEM" : "Civil alignment"}</Button>)}</div>
    {error && <p role="alert" className="rounded-xl border border-rose-800 bg-rose-950/40 p-3 text-rose-200">{error}</p>}
    {tab === "bim" && <Card className="space-y-4 p-5">
      <h2 className="text-lg font-semibold">IFC geometry and stable source exchange</h2><p className="text-sm text-slate-400">Supported IFC2X3/IFC4 schema editions: local placements, rectangular/circular/simple polygon extrusion, triangle sets, polygonal BRep faces and uniform 3D mapped instances with an identity mapping origin. Source geometry and GlobalIds remain in IFC exports. Openings, Boolean operations and other mapped transforms retain explicit coverage limits.</p>
      <label className="block text-sm">Import IFC (20 MB)<input className="mt-2 block w-full" type="file" accept=".ifc" disabled={busy} onChange={event => { void importFile(event, "ifc"); }} /></label>
      {ifc && <><p>{ifc.schema} · {ifc.products.length} products · {ifc.unitScale} metres per source unit</p><Plan lines={meshLines} /><p className="text-xs text-slate-400">Plan projection shows up to 2000 supported triangles; full supported meshes are included in OBJ export.</p>
        {ifcDeclaration?.provenance && <p className="text-xs text-slate-300">Captured engineering country: {ifcDeclaration.provenance.designBasis?.countryCode || "undeclared"}. National-code compliance remains not assessed. Export metadata to retain the complete adopted-edition declaration.</p>}
        {!!ifcDeclaration?.provenance?.declarationIssues.length && <div className="text-xs text-amber-200"><p>Engineering declaration review findings ({ifcDeclaration.provenance.declarationIssues.length}); showing up to 10. The full findings remain in the metadata export.</p><ul className="list-disc pl-4">{ifcDeclaration.provenance.declarationIssues.slice(0, 10).map((issue, index) => <li key={index}>{issue}</li>)}</ul></div>}
        {!!ifcDeclaration?.issues.length && <p className="text-xs text-amber-200">{ifcDeclaration.issues.slice(0, 3).join(" ")} Declaration findings are retained in the metadata export.</p>}
        <div className="grid gap-3 md:grid-cols-2"><Select label="Product to rename" value={selected} onChange={event => setSelected(event.target.value)}>{ifc.products.slice(0, 500).map(p => <option key={p.stepId} value={p.globalId}>{p.type} · {p.name || p.globalId}</option>)}</Select>{product && <Input label="Exported name" value={names[product.globalId] ?? product.name} maxLength={1024} onChange={event => { setNames({ ...names, [product.globalId]: event.target.value }); setBimReport(undefined); setBimReportKind(null); }} />}</div>
        {product && <pre className="max-h-40 overflow-auto rounded bg-slate-950 p-3 text-xs">{JSON.stringify({ globalId: product.globalId, attributes: product.attributes, declaredType: product.declaredType, propertyValues: product.propertyValues, properties: product.properties, metadataIssues: product.metadataIssues, issues: product.issues }, null, 2)}</pre>}
        <h3 className="font-semibold">Existing scalar property edits</h3><p className="text-xs text-slate-400">Edit up to 100 existing direct occurrence properties by exact product GlobalId, property-set name and property name. Keep the existing text, boolean, integer or real type. Shared, inherited, ambiguous and unit-bearing properties require a separate authoring tool. The saved draft applies to IFC/metadata exports and IDS checks; imported source and its geometry remain available.</p>
        <textarea aria-label="IFC property edit draft" className={textareaClass} value={propertyEditsText} maxLength={250000} onChange={event => { setPropertyEditsText(event.target.value); setBimReport(undefined); setBimReportKind(null); }} />
        <div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!product} onClick={() => { if (!product) return; const property = Object.values(product.propertyValues ?? {}).find(value => value.supported && value.origin === "occurrence" && value.unit === null && value.value !== null && ["IFCLABEL", "IFCTEXT", "IFCIDENTIFIER", "IFCBOOLEAN", "IFCINTEGER", "IFCREAL"].includes(value.dataType)); if (!property) { setError("This product has no supported existing unitless scalar property to use as an edit template."); return; } setPropertyEditsText(JSON.stringify({ version: 1, edits: [{ productGlobalId: product.globalId, propertySet: property.propertySet, name: property.name, dataType: property.dataType, value: property.value }] }, null, 2)); setBimReport(undefined); setBimReportKind(null); setError(""); }}>Replace draft with selected product template</Button><Button variant="secondary" onClick={() => { setPropertyEditsText(emptyPropertyEdits); setBimReport(undefined); setBimReportKind(null); }}>Clear property edits</Button></div>
        <div className="flex flex-wrap gap-2"><Button onClick={() => perform(() => download("roundtrip.ifc", editedIfc(ifc, propertyEditsText, names).source, "application/x-step"))}>Export edited IFC</Button><Button variant="secondary" onClick={() => download("original-source.ifc", ifc.source, "application/x-step")}>Export original IFC</Button><Button variant="secondary" onClick={() => perform(() => download("supported-geometry.obj", exportIfcMeshObj(ifc), "text/plain"))}>Export supported OBJ</Button><Button variant="secondary" onClick={() => perform(() => { const document = editedIfc(ifc, propertyEditsText, names); download("ifc-metadata.json", JSON.stringify({ schema: document.schema, engineeringDeclaration: inspectIfcEngineeringDeclaration(document), products: document.products.map(({ meshes, ...p }) => ({ ...p, meshParts: meshes.length })), issues: document.issues }, null, 2)); })}>Export edited metadata</Button></div>
        <Button variant="secondary" onClick={() => perform(() => download("geometry-scene.json", JSON.stringify(ifcScene(ifc))))}>Export geometry scene for clash / rendering workbench</Button>
        <h3 className="font-semibold">IDS requirements</h3><p className="text-xs text-slate-400">Literal entity, supported predefined type, string attributes and single-value properties are checked using the edited export draft. Supported length, area, volume, mass, time and plane-angle values use declared SI units and prefixes for numeric comparison; the original property values and unit records are retained. Floating equality follows the documented IDS precision band. Missing or ambiguous units, conversion/offset/compound units, subtype inheritance, restrictions, classification, materials and parts facets produce an incomplete report.</p><input aria-label="Import IDS XML" type="file" accept=".ids,.xml" disabled={busy} onChange={event => { void importFile(event, "ids"); }} /><textarea aria-label="IDS XML" className={textareaClass} value={idsText} maxLength={2000000} onChange={event => { setIdsText(event.target.value); setBimReport(undefined); setBimReportKind(null); }} />
        <div className="flex flex-wrap gap-2"><Button disabled={!idsText} onClick={() => perform(() => { const report = validateIds(editedIfc(ifc, propertyEditsText, names), idsText); setBimReport(report); setBimReportKind("ids"); })}>Check supported IDS requirements</Button><Button variant="secondary" onClick={() => { setBimReport(inspectBimGeometry(ifc)); setBimReportKind("geometry"); }}>Geometry coverage</Button>{bimReport && <Button variant="secondary" onClick={() => download("bim-validation.json", JSON.stringify(bimReport, null, 2))}>Export report</Button>}</div>{bimReport && <Findings report={bimReport} />}
      </>}
    </Card>}
    {tab === "survey" && <Card className="space-y-4 p-5"><h2 className="text-lg font-semibold">Survey reprojection and constrained terrain</h2><p className="text-sm text-slate-400">CSV easting,northing,elevation; uncompressed LAS 1.1–1.4; classic uncompressed single-band north-up GeoTIFF DEM. Binary inputs are sampled to at most 2000 points. Imported coordinates retain source units. Declare units, axes and the unchanged vertical datum before terrain generation.</p><input aria-label="Import survey" type="file" accept=".csv,.txt,.las,.tif,.tiff" disabled={busy} onChange={event => { void importFile(event, "survey"); }} />
      {survey && <><p>{survey.points.length} sampled points from {survey.originalCount} records/cells.</p><ul className="text-xs text-amber-200">{survey.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul>{surveyProjectFrame && <p className="text-xs text-slate-400">Project survey frame retained: {surveyProjectFrame.projectCrs}; origin {surveyProjectFrame.originEastingM} / {surveyProjectFrame.originNorthingM} m; imported coordinates {surveyProjectFrame.coordinates}. Elevation datum remains unchanged.</p>}<div className="grid gap-3 md:grid-cols-2"><Input label="Source CRS (LOCAL or EPSG code)" value={fromCrs} maxLength={100} onChange={event => { setFromCrs(event.target.value); setSurface(undefined); setCivilReport(undefined); }} /><Input label="Target CRS (LOCAL or EPSG code)" value={toCrs} maxLength={100} onChange={event => { setToCrs(event.target.value); setSurface(undefined); setCivilReport(undefined); }} /></div><p className="text-xs text-slate-400">WGS84 longitude/latitude EPSG:4326, Web Mercator EPSG:3857, WGS84 UTM EPSG:32601–32660 / 32701–32760. LOCAL retains surveyed metre coordinates; no georeferencing is inferred. Terrain and civil work require projected metre coordinates.</p>
        {survey.coordinateMetadata && <details className="text-xs"><summary>Imported coordinate reference records · {survey.coordinateMetadata.status}</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap">{JSON.stringify(survey.coordinateMetadata, null, 2)}</pre></details>}
        <label className="block text-sm">Reviewed survey coordinate declaration<textarea aria-label="Survey coordinate declaration" className={`${textareaClass} mt-2`} value={surveyDeclarationText} maxLength={10000} onChange={event => { setSurveyDeclarationText(event.target.value); setSurface(undefined); setCivilReport(undefined); }} /></label><p className="text-xs text-slate-400">Set horizontalCrs to the source CRS; units to m, international-foot or us-survey-foot (degree for EPSG:4326); axes to east-north or lon-lat. Supply elevationUnit, the exact verticalDatum name or EPSG identifier, and your survey source/review reference. Only declared linear units are scaled. Axis swaps, conflicting file metadata and unsupported reference systems are rejected. No vertical datum transformation is performed.</p>
        <label className="block text-sm">Breaklines and terrain holes (zero-based indices into imported points)<textarea className={`${textareaClass} mt-2`} value={constraints} maxLength={50000} onChange={event => { setConstraints(event.target.value); setSurface(undefined); setCivilReport(undefined); }} /></label><Button onClick={() => perform(() => { const sourceCrs = fromCrs.trim().toUpperCase(), targetCrs = toCrs.trim().toUpperCase(), nextSurface = buildWorkspaceSurface(survey, sourceCrs, targetCrs, constraints, surveyDeclarationText, surveyProjectFrame); setSurface(nextSurface); setFromCrs(sourceCrs); setToCrs(targetCrs); setCivilReport(undefined); })}>Transform and build constrained surface</Button>
        {surface && <><Plan lines={surfaceLines} /><p className="text-xs text-slate-400">{surface.triangles.length} triangles; plan projection shows up to 2000. Constraints and holes refer to the complete point list.</p><ul className="text-xs text-amber-200">{surface.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => perform(() => download("survey-surface.json", JSON.stringify({ crs: toCrs, coordinateProvenance: prepareSurveyForTerrain(survey, JSON.parse(surveyDeclarationText) as unknown).provenance, ...surface }, null, 2)))}>Export transformed surface</Button><Button variant="secondary" onClick={() => perform(() => download("surface-drainage.json", JSON.stringify({ crs: toCrs, coordinateProvenance: prepareSurveyForTerrain(survey, JSON.parse(surveyDeclarationText) as unknown).provenance, ...routeSurfaceDrainage(surface), limitation: "Steepest mesh vertex descent; sinks retained; no hydraulic or pit-fill model." }, null, 2)))}>Export drainage routes</Button></div></>}
        {surface && <Button variant="secondary" onClick={() => perform(() => download("geometry-scene.json", JSON.stringify(geometryScene([{ id: "survey-surface", sourceId: "survey-surface", positions: surface.points.flatMap(p => [p.x, p.elevationM, -p.z]), indices: surface.triangles.flat(), material: { color: [.45, .55, .3], emission: [0, 0, 0], model: "diffuse", ior: 1.5 } }], [...surface.warnings, `Projected CRS ${toCrs}; y is metre elevation and z is negative northing.`]))))}>Export terrain geometry scene</Button>}
      </>}
    </Card>}
    {tab === "civil" && <Card className="space-y-4 p-5"><h2 className="text-lg font-semibold">Circular / clothoid / parabolic alignment</h2><p className="text-sm text-slate-400">JSON defines connected horizontal segments, continuous parabolic vertical curves and superelevation stations. Signed arc radius and curvature turn left when positive. Positive superelevation raises the left edge. Survey surface: {surface ? `${surface.triangles.length} triangles in ${toCrs}` : "none; geometry and profile only"}.</p><textarea aria-label="Civil alignment JSON in metres" className={`${textareaClass} min-h-96`} value={alignment} maxLength={100000} onChange={event => { setAlignment(event.target.value); setCivilReport(undefined); }} /><Button onClick={() => perform(() => setCivilReport(analyzeAdvancedCivil(parseAdvancedAlignment(alignment), surface)))}>Calculate alignment and earthworks</Button>
      {civilReport && <><Plan lines={[civilReport.stations.flatMap(s => [s.x, s.z])]} /><p>{civilReport.lengthM.toFixed(2)} m · {civilReport.stations.length} stations · cut {civilReport.cutM3.toFixed(2)} m³ · fill {civilReport.fillM3.toFixed(2)} m³ · quantified {civilReport.quantifiedLengthM.toFixed(2)} m</p><ul className="text-xs text-amber-200">{civilReport.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => download("civil-alignment-report.json", JSON.stringify({ crs: surface ? toCrs : "LOCAL", ...(surface && survey ? { coordinateProvenance: prepareSurveyForTerrain(survey, JSON.parse(surveyDeclarationText) as unknown).provenance } : {}), alignment: parseAdvancedAlignment(alignment), ...civilReport }, null, 2))}>Export alignment / sections JSON</Button><Button variant="secondary" onClick={() => download("civil-stations.csv", advancedCivilCsv(civilReport), "text/csv")}>Export station CSV</Button></div></>}
    </Card>}
  </main>;
}
